#pragma once

#include <c2h/catch2_test_helper.h>

#define CUB_TEST_MEMORY_TAG_CUB_SMALL "[small-mem]"
#define CUB_TEST_MEMORY_TAG_CUB_LARGE "[large-mem]"
#define CUB_TEST_MEMORY_TAG(MEMORY)   C2H_TEST_CONCAT(CUB_TEST_MEMORY_TAG_, MEMORY)

#define CUB_TEST(NAME, TAGS, MEMORY, ...) C2H_TEST(NAME, TAGS CUB_TEST_MEMORY_TAG(MEMORY), __VA_ARGS__)

#define CUB_TEST_LIST(NAME, TAGS, MEMORY, ...) C2H_TEST_LIST(NAME, TAGS CUB_TEST_MEMORY_TAG(MEMORY), __VA_ARGS__)
