# Recording shims for the registration-replay parity harness.
# Included by each side's wrapper CMakeLists.txt AFTER project(),
# BEFORE including the registration file under test.
# Required cache vars: ROW, REPO, RAPIDS_SRC.

# ---- matrix row presets (plain vars; CMP0077 makes option() respect them) --
set(CUB_ENABLE_LAUNCH_NO_LAUNCHER ON)
set(CUB_ENABLE_LAUNCH_HOST_LAUNCHER ON)
set(CUB_ENABLE_LAUNCH_DEVICE_LAUNCHER ON)
set(CUB_ENABLE_LAUNCH_GRAPH_LAUNCHER ON)
set(CUB_ENABLE_RDC_TESTS ON)
set(CUB_FORCE_RDC OFF)
set(CMAKE_CXX_COMPILER_ID "GNU")
set(CMAKE_CXX_COMPILER_VERSION "13.2.0")
set(CMAKE_CUDA_COMPILER_ID "NVIDIA")
set(CMAKE_CUDA_COMPILER_VERSION "12.9.0")

if (ROW STREQUAL "base")
elseif (ROW STREQUAL "forcerdc")
  set(CUB_FORCE_RDC ON)
elseif (ROW STREQUAL "nordc")
  set(CUB_ENABLE_RDC_TESTS OFF)
elseif (ROW STREQUAL "hostonly")
  set(CUB_ENABLE_LAUNCH_DEVICE_LAUNCHER OFF)
  set(CUB_ENABLE_LAUNCH_GRAPH_LAUNCHER OFF)
elseif (ROW STREQUAL "nolauncher")
  set(CUB_ENABLE_LAUNCH_NO_LAUNCHER OFF)
elseif (ROW STREQUAL "clanghost")
  set(CMAKE_CXX_COMPILER_ID "Clang")
  set(CMAKE_CXX_COMPILER_VERSION "14.0.0")
  set(CMAKE_CUDA_COMPILER_VERSION "13.1.0") # also exercises future_arch
elseif (ROW STREQUAL "tile")
  set(CCCL_ENABLE_EXPERIMENTAL_TILE_TRANSFORM_DISPATCH ON)
elseif (ROW STREQUAL "clangcuda")
  set(CMAKE_CUDA_COMPILER_ID "Clang")
  set(CMAKE_CUDA_COMPILER_VERSION "22.1.0") # -Wno-pass-failed tail quirk
else()
  message(FATAL_ERROR "unknown ROW=${ROW}")
endif()

# ---- event recorder ---------------------------------------------------------
string(ASCII 31 _replay_us) # unit separator: survives inside recorded args
set_property(GLOBAL PROPERTY replay_events "")
function(_record kind)
  set(line "${kind}")
  foreach (arg IN LISTS ARGN)
    string(APPEND line "${_replay_us}${arg}")
  endforeach()
  set_property(GLOBAL APPEND PROPERTY replay_events "${line}")
endfunction()
function(replay_dump)
  get_property(events GLOBAL PROPERTY replay_events)
  list(JOIN events "\n" events)
  file(WRITE "${CMAKE_BINARY_DIR}/events.log" "${events}\n")
  message(STATUS "replay: wrote ${CMAKE_BINARY_DIR}/events.log")
endfunction()

# ---- shadowed built-ins (originals available as _<name>) --------------------
function(add_test)
  _record(add_test ${ARGV})
endfunction()
function(set_tests_properties)
  _record(set_tests_properties ${ARGV})
endfunction()
function(set_target_properties)
  _record(set_target_properties ${ARGV})
endfunction()
function(set_property kind)
  if (kind STREQUAL "TEST")
    _record(set_property ${ARGV})
  else()
    _set_property(${ARGV})
  endif()
endfunction()
function(add_library name)
  _record(add_library ${ARGV})
  if (NOT TARGET ${name})
    _add_library(${name} INTERFACE)
  endif()
endfunction()
function(add_executable name)
  _record(add_executable ${ARGV})
  if (NOT TARGET ${name})
    _add_library(${name} INTERFACE)
  endif()
endfunction()
function(target_link_libraries)
  _record(target_link_libraries ${ARGV})
endfunction()
function(target_include_directories)
  _record(target_include_directories ${ARGV})
endfunction()
function(target_compile_definitions)
  _record(target_compile_definitions ${ARGV})
endfunction()
function(target_compile_options)
  _record(target_compile_options ${ARGV})
endfunction()
function(target_compile_features)
  _record(target_compile_features ${ARGV})
endfunction()
function(add_subdirectory)
  _record(add_subdirectory ${ARGV})
endfunction()
function(configure_file)
  _record(configure_file ${ARGV})
endfunction()
function(add_dependencies)
  _record(add_dependencies ${ARGV})
endfunction()
function(add_custom_target name)
  _record(add_custom_target ${ARGV})
  if (NOT TARGET ${name})
    _add_library(${name} INTERFACE)
  endif()
endfunction()
function(install)
  _record(install ${ARGV})
endfunction()

# ---- CCCL shared-infra stand-ins --------------------------------------------
macro(cccl_get_c2h)
endmacro()
macro(cccl_get_cudatoolkit)
endmacro()
macro(cccl_get_nvtx)
endmacro()
function(cccl_configure_target)
  _record(cccl_configure_target ${ARGV})
endfunction()
function(cccl_ensure_metatargets)
  _record(cccl_ensure_metatargets ${ARGV})
endfunction()
function(cccl_add_executable name)
  _record(cccl_add_executable ${ARGV})
  if (NOT TARGET ${name})
    _add_library(${name} INTERFACE)
  endif()
endfunction()
macro(cccl_get_rapids_test)
  set(rapids-cmake_SOURCE_DIR "${RAPIDS_SRC}")
  # rapids' spec generator requires an enabled CXX/CUDA language; the replay
  # project is LANGUAGES NONE, so fake the global property it checks:
  include("${RAPIDS_SRC}/rapids-cmake/test/init.cmake")
  include("${RAPIDS_SRC}/rapids-cmake/test/gpu_requirements.cmake")
  # Pre-include the spec generator so its include_guard(GLOBAL) blocks the
  # re-include rapids_test_init() performs at call time; then replace it
  # with a recorder (the real one fatals under LANGUAGES NONE). Identical on
  # both replay sides, so parity comparisons are unaffected.
  include("${RAPIDS_SRC}/rapids-cmake/test/generate_resource_spec.cmake")
  function(rapids_test_generate_resource_spec DESTINATION filepath)
    _record(rapids_test_generate_resource_spec ${ARGV})
  endfunction()
endmacro()

# ---- real shared implementations (they call only shadowed primitives) -------
include("${REPO}/cmake/CCCLTestParams.cmake")
include("${REPO}/cmake/CCCLUtilities.cmake")
include("${REPO}/cub/cmake/CubUtilities.cmake")
